BrowserPolicy.content.allowOriginForAll("*.googleapis.com");
BrowserPolicy.content.allowOriginForAll("*.gstatic.com");
BrowserPolicy.content.allowOriginForAll("*.bootstrapcdn.com");
BrowserPolicy.content.allowOriginForAll("*.amazonaws.com");
BrowserPolicy.content.allowOriginForAll("http://");
BrowserPolicy.content.allowOriginForAll("https://");
BrowserPolicy.content.allowOriginForAll("blob:");
BrowserPolicy.content.allowEval();
BrowserPolicy.content.allowImageSameOrigin();
BrowserPolicy.content.allowImageOrigin("blob:");
BrowserPolicy.content.allowImageOrigin( "*.amazonaws.com" );
BrowserPolicy.content.allowFontDataUrl();
BrowserPolicy.content.allowOriginForAll('*.google.com/*');
BrowserPolicy.content.allowOriginForAll('*.googleapis.com/*');
BrowserPolicy.content.allowOriginForAll('*.gstatic.com/*');
